swagger: '2.0'
info:
  title: WebSocket
  x-ibm-name: websocket
  version: 1.0.0
  description: Used To Authenticate and Authorize WebSocket calls
schemes:
  - https
basePath: /websocket
security:
  - clientID: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - set-variable:
          version: 1.0.0
          title: set-variable
          actions:
            - set: message.body
              value: SUCCESS
    catch: []
  properties:
    target-url:
      value: 'http://example.com/operation-name'
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
paths:
  /:
    get:
      responses:
        '200':
          description: ok
          schema:
            type: string
      consumes: []
      produces: []